version: "2.1"

services:
  # CLI
  cli:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: cli
    environment:
      - PHP_IDE_CONFIG
      - SYMFONY_REQUIRE

#  # Memcached
#  memcached:
#    extends:
#      file: ${HOME}/.docksal/stacks/services.yml
#      service: memcached
#
#  # Solr
#  solr:
#    extends:
#      file: ${HOME}/.docksal/stacks/services.yml
#      service: solr

  # Browser
  browser:
    hostname: browser
    image: selenium/standalone-chrome-debug
    volumes:
      # Project root volume
      - project_root:/var/www:ro,nocopy
    ports:
      - "${VNC_PORT_MAPPING:-5900}"
    dns:
      - ${DOCKSAL_DNS1}
      - ${DOCKSAL_DNS2}